# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberapp', '0001_initial'),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(db_column='good_count', verbose_name='数量')),
                ('good', models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='memberapp.Goods')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'db_table': 'CartInfo',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=100, verbose_name='订单号')),
                ('order_time', models.DateTimeField(auto_now=True, verbose_name='订单时间')),
                ('ads_name', models.CharField(max_length=30, verbose_name='收货人')),
                ('ads_phone', models.IntegerField(max_length=11, verbose_name='联系电话')),
                ('ads', models.CharField(max_length=150, verbose_name='地址')),
                ('total', models.IntegerField(verbose_name='总数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价格')),
                ('order_detail', models.TextField(blank=True, null=True, verbose_name='订单详情')),
                ('order_status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
