# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ads_phone',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
    ]
