# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('手机号码', models.CharField(max_length=11)),
                ('用户密码', models.CharField(max_length=20)),
                ('用户昵称', models.CharField(max_length=20)),
                ('电子邮箱', models.EmailField(max_length=254, null=True)),
                ('激活状态', models.BooleanField(default=True)),
            ],
        ),
    ]
