# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/image/goods', verbose_name='商品图片')),
                ('desc', models.CharField(max_length=200, verbose_name='商品描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='下架')),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='无', max_length=20, verbose_name='商品类型')),
                ('desc', models.CharField(default='类别描述', max_length=300, verbose_name='类别描述')),
                ('flag', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'db_table': 'GoodType',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodType'),
        ),
    ]
