# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='收货人')),
                ('address', models.CharField(db_column='address', max_length=150, verbose_name='地址')),
                ('phone', models.IntegerField(db_column='phone', max_length=11, verbose_name='手机号码')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='用户名')),
                ('password', models.CharField(db_column='password', max_length=20, verbose_name='密码')),
                ('phone', models.IntegerField(db_column='phone', max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(db_column='email', max_length=40, verbose_name='电子邮箱')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
                ('is_ban', models.BooleanField(default=False, verbose_name='禁用')),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo'),
        ),
    ]
