# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('website', models.URLField()),
            ],
        ),
    ]
