# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180625_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='age',
            field=models.SmallIntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
