# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_goods_goodstype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品名称'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spec',
            field=models.CharField(max_length=30, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='desc',
            field=models.TextField(null=True, verbose_name='商品类型描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goodstype', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=20, verbose_name='类型'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='goodstype',
        ),
    ]
